# Pipeline Configuration File
# All paths can be absolute or relative

paths:
  xml_input: /Users/noahkim/Documents/UTPS/Traffic_Sim/utps-ts-repo/data/interim/20_min.xml
  gpkg_network: /Users/noahkim/Documents/UTPS/Traffic_Sim/utps-ts-repo/data/raw/road_network_v4_clipped_single.gpkg
  parquet_intermediate: /Users/noahkim/Documents/UTPS/Traffic_Sim/utps-ts-repo/data/interim/filtered_events_test.parquet
  geojson_output: /Users/noahkim/Documents/UTPS/Traffic_Sim/utps-ts-repo/data/processed/trajectories_test.geojson

filters:
  # First time interval (format: hh:mm)
  time_interval_1:
    start: "00:00"
    end: "23:39"
  
  # Second time interval (use same as first for single interval filtering)
  time_interval_2:
    start: "00:00"
    end: "23:39"

processing:
  # Number of worker processes (omit to use all CPUs)
  num_workers: 6
  
  # Chunk size for processing (larger = more memory, faster processing)
  chunk_size: 30000

# Skip steps if intermediate files already exist
skip_xml_to_parquet: false
skip_parquet_to_geojson: false
